@php($editing = (bool) $role)
<x-admin-layout :title="$editing ? 'Edit Role' : 'Create Role'">
    @include('admin.access._tabs')
    <div class="mx-auto max-w-4xl"><a href="{{ route('admin.roles') }}" class="mb-5 inline-flex text-sm font-semibold text-slate-600 hover:text-indigo-600">← Back to Roles</a><form method="POST" action="{{ $editing ? route('admin.roles.update', $role) : route('admin.roles.store') }}" class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" x-data="{ saving: false }" @submit="saving = true">@csrf @if($editing) @method('PATCH') @endif
        <div class="border-b border-slate-200 px-6 py-5"><h2 class="font-display text-lg font-semibold">{{ $editing ? 'Edit role' : 'Create role' }}</h2><p class="mt-1 text-sm text-slate-500">Define the role and select its exact permissions.</p></div>
        <div class="grid gap-5 p-6 sm:grid-cols-2"><label><span class="mb-1.5 block text-sm font-semibold">Role Name *</span><input name="name" value="{{ old('name', $role?->name) }}" required @readonly($role?->is_system) class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200 disabled:bg-slate-50">@if($role?->is_system)<span class="mt-1 block text-xs text-slate-500">System role names are fixed because authorization depends on them.</span>@endif @error('name')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label><label class="sm:col-span-2"><span class="mb-1.5 block text-sm font-semibold">Description</span><textarea name="description" rows="3" class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">{{ old('description', $role?->description) }}</textarea></label></div>
        <div class="border-t border-slate-200 px-6 py-5"><div class="flex items-center justify-between"><div><h3 class="font-display font-semibold">Permissions</h3><p class="mt-1 text-sm text-slate-500">Only selected capabilities will be assigned.</p></div><span class="text-xs font-semibold text-slate-500">{{ $permissions->flatten()->count() }} available</span></div><div class="mt-5 grid gap-4 md:grid-cols-2">@foreach($permissions as $group => $groupPermissions)<fieldset class="rounded-xl border border-slate-200 p-4"><legend class="px-1 text-sm font-bold text-slate-800">{{ $group }}</legend><div class="mt-2 space-y-2">@foreach($groupPermissions as $permission)<label class="flex cursor-pointer gap-3 rounded-lg p-2 hover:bg-slate-50"><input type="checkbox" name="permission_ids[]" value="{{ $permission->id }}" @checked(in_array($permission->id, old('permission_ids', $role?->permissions?->pluck('id')->all() ?? []))) class="mt-0.5 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"><span><span class="block text-sm font-semibold">{{ $permission->name }}</span><span class="block text-xs text-slate-500">{{ $permission->description ?: 'No description' }}</span></span></label>@endforeach</div></fieldset>@endforeach</div>@error('permission_ids.*')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div class="flex justify-end gap-3 border-t border-slate-200 bg-slate-50 px-6 py-4"><a href="{{ route('admin.roles') }}" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">Cancel</a><button :disabled="saving" class="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-semibold text-white disabled:opacity-60" x-text="saving ? 'Saving...' : '{{ $editing ? 'Update Role' : 'Create Role' }}'">Save</button></div>
    </form></div>
</x-admin-layout>
