<x-admin-layout title="Roles & Permissions">
    @include('admin.access._tabs')
    <div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="font-display text-xl font-bold">Role Management</h2><p class="mt-1 text-sm text-slate-500">Create roles and define their permission sets.</p></div><a href="{{ route('admin.roles.create') }}" class="inline-flex items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><x-ui.icon name="plus" class="h-4 w-4" /> Create Role</a></div>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <form method="GET" class="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row"><label class="flex max-w-xl flex-1 items-center rounded-lg border border-slate-200 px-3"><x-ui.icon name="magnifying-glass" class="h-4 w-4 text-slate-400" /><input name="search" value="{{ request('search') }}" class="w-full border-0 bg-transparent px-2 py-2 text-sm focus:ring-0" placeholder="Search roles..."></label><button class="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold hover:bg-slate-50">Search</button></form>
        <div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left"><thead class="border-b border-slate-200 bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Role</th><th class="px-4 py-3">Description</th><th class="px-4 py-3">Users</th><th class="px-4 py-3">Permissions</th><th class="px-4 py-3">Type</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 text-sm">
            @forelse($roles as $role)<tr class="hover:bg-slate-50"><td class="px-4 py-3"><a href="{{ route('admin.roles.show', $role) }}" class="font-semibold text-slate-900 hover:text-indigo-600">{{ Str::headline($role->name) }}</a></td><td class="max-w-xs px-4 py-3 text-slate-500"><span class="block truncate">{{ $role->description ?: 'No description' }}</span></td><td class="px-4 py-3">{{ $role->users_count }}</td><td class="px-4 py-3">{{ $role->permissions_count }}</td><td class="px-4 py-3"><span class="rounded-full px-2 py-1 text-xs font-semibold {{ $role->is_system ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600' }}">{{ $role->is_system ? 'System' : 'Custom' }}</span></td><td class="px-4 py-3"><div class="flex justify-end gap-1"><a href="{{ route('admin.roles.show', $role) }}" class="rounded-lg p-2 text-slate-500 hover:bg-indigo-50 hover:text-indigo-600"><x-ui.icon name="eye" class="h-4 w-4" /></a><a href="{{ route('admin.roles.edit', $role) }}" class="rounded-lg p-2 text-slate-500 hover:bg-blue-50 hover:text-blue-600"><x-ui.icon name="pencil-square" class="h-4 w-4" /></a>@can('delete', $role)<form method="POST" action="{{ route('admin.roles.destroy', $role) }}" onsubmit="return confirm('Delete this role?')">@csrf @method('DELETE')<button class="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600"><x-ui.icon name="trash" class="h-4 w-4" /></button></form>@endcan</div></td></tr>
            @empty<tr><td colspan="6" class="px-6 py-16 text-center"><p class="font-semibold">No roles found</p><p class="mt-1 text-sm text-slate-500">Create a role to begin assigning access.</p></td></tr>@endforelse
        </tbody></table></div>@if($roles->hasPages())<div class="border-t border-slate-200 px-4 py-3">{{ $roles->links() }}</div>@endif
    </section>
</x-admin-layout>
