@php($editing = (bool)$template)
<x-admin-layout :title="$editing ? 'Edit Template' : 'Upload Template'">
    <div class="mx-auto max-w-6xl" x-data="{saving:false}">
        <a href="{{ route('admin.templates') }}" class="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-indigo-600">← Back to Templates</a>
        <form method="POST" enctype="multipart/form-data" action="{{ $editing?route('admin.templates.update',$template):route('admin.templates.store') }}" @submit="saving=true" class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]">@csrf @if($editing)@method('PATCH')@endif
            <section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-6 py-5"><h2 class="text-lg font-semibold">{{ $editing?'Edit template metadata':'Register a resume template' }}</h2><p class="mt-1 text-sm text-slate-500">Upload safe placeholder-based HTML; no project code changes are required.</p></div>
                <div class="grid gap-5 p-6 md:grid-cols-2">
                    <label><span class="mb-1.5 block text-sm font-semibold">Name *</span><input name="name" value="{{ old('name',$template?->name) }}" required class="w-full rounded-lg border-slate-200 text-sm"></label>
                    <label><span class="mb-1.5 block text-sm font-semibold">Slug *</span><input name="slug" value="{{ old('slug',$template?->slug) }}" required pattern="[A-Za-z0-9_-]+" class="w-full rounded-lg border-slate-200 text-sm"></label>
                    <label><span class="mb-1.5 block text-sm font-semibold">Category</span><select name="template_category_id" class="w-full rounded-lg border-slate-200 text-sm"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)old('template_category_id',$template?->template_category_id)===$category->id)>{{ $category->name }}</option>@endforeach</select></label>
                    <label><span class="mb-1.5 block text-sm font-semibold">Status *</span><select name="status" required class="w-full rounded-lg border-slate-200 text-sm">@foreach(['draft'=>'Draft','published'=>'Published','disabled'=>'Disabled'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$template?->status??'draft')===$value)>{{ $label }}</option>@endforeach</select></label>
                    <label class="md:col-span-2"><span class="mb-1.5 block text-sm font-semibold">Description</span><textarea name="description" rows="3" class="w-full rounded-lg border-slate-200 text-sm">{{ old('description',$template?->description) }}</textarea></label>
                    <label><span class="mb-1.5 block text-sm font-semibold">Primary Color *</span><input name="primary_color" type="color" value="{{ old('primary_color',data_get($template?->config,'primary_color','#4f46e5')) }}" required class="h-10 w-full rounded-lg border-slate-200"></label>
                    <label><span class="mb-1.5 block text-sm font-semibold">Font Family *</span><input name="font_family" value="{{ old('font_family',data_get($template?->config,'font_family','Inter, Arial, sans-serif')) }}" required class="w-full rounded-lg border-slate-200 text-sm"></label>
                    <label><span class="mb-1.5 block text-sm font-semibold">Display Order *</span><input name="sort_order" type="number" min="0" value="{{ old('sort_order',$template?->sort_order??0) }}" required class="w-full rounded-lg border-slate-200 text-sm"></label>
                    <div class="flex items-end gap-5 pb-2"><label class="flex items-center gap-2 text-sm font-semibold"><input type="hidden" name="is_featured" value="0"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$template?->is_featured)) class="rounded border-slate-300 text-indigo-600"> Featured</label><label class="flex items-center gap-2 text-sm font-semibold"><input type="hidden" name="is_premium" value="0"><input type="checkbox" name="is_premium" value="1" @checked(old('is_premium',$template?->is_premium)) class="rounded border-slate-300 text-indigo-600"> Premium</label></div>
                    <fieldset class="md:col-span-2"><legend class="mb-2 text-sm font-semibold">Supported Sections *</legend><div class="grid gap-2 sm:grid-cols-3">@foreach($sections as $key=>$label)<label class="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="supported_sections[]" value="{{ $key }}" @checked(in_array($key,old('supported_sections',data_get($template?->config,'supported_sections',array_keys($sections->all()))),true)) class="rounded border-slate-300 text-indigo-600">{{ $label }}</label>@endforeach</div></fieldset>
                    <div class="space-y-2 md:col-span-2"><span class="block text-sm font-semibold">Preview image URLs <span class="font-normal text-slate-400">(up to 5)</span></span>@for($index=0;$index<5;$index++)<input name="preview_images[]" type="url" value="{{ old('preview_images.'.$index,data_get($template?->config,'preview_images.'.$index)) }}" class="w-full rounded-lg border-slate-200 text-sm" placeholder="https://example.com/preview-{{ $index+1 }}.png">@endfor</div>
                </div>
                @if($errors->any())<div class="mx-6 mb-5 rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><p class="font-semibold">Please correct the following:</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
                <div class="flex justify-end gap-3 border-t border-slate-200 bg-slate-50 px-6 py-4"><a href="{{ route('admin.templates') }}" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">Cancel</a><button :disabled="saving" class="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-semibold text-white disabled:opacity-60" x-text="saving?'Saving...':'{{ $editing?'Save Changes':'Upload Template' }}'">Save</button></div>
            </section>
            <aside class="space-y-4"><section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 class="font-semibold">Template Source {{ $editing?'':'*' }}</h3><label class="mt-3 flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-indigo-400 bg-indigo-50/30 p-4 text-center"><x-ui.icon name="document-arrow-up" class="h-8 w-8 text-indigo-600"/><span class="mt-2 text-sm font-semibold">Choose HTML or TXT</span><span class="text-xs text-slate-500">Maximum 5MB</span><input type="file" name="template_file" accept=".html,.htm,.txt,text/html,text/plain" {{ $editing?'':'required' }} class="mt-3 block w-full text-xs"></label>@if($editing)<p class="mt-2 text-xs text-slate-500">Current version {{ $template->version }}. Leave empty to retain it.</p>@endif</section>
                <section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 class="font-semibold">Thumbnail</h3><input type="file" name="thumbnail" accept="image/png,image/jpeg,image/webp" class="mt-3 block w-full text-xs"><p class="mt-2 text-xs text-slate-500">PNG, JPG or WEBP. Maximum 2MB.</p></section>
                <section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 class="font-semibold">Available placeholders</h3><div class="mt-3 flex flex-wrap gap-1.5">@foreach($placeholders as $key=>$label)<code class="rounded bg-indigo-50 px-1.5 py-1 text-[10px] text-indigo-700">@{{ {{ $key }} }}</code>@endforeach</div></section>
            </aside>
        </form>
    </div>
</x-admin-layout>
