<x-admin-layout :title="$template->name.' Preview'">
    <div class="space-y-4">
        <div class="flex flex-wrap items-center justify-between gap-3">
            <div><a href="{{ route('admin.templates') }}" class="text-sm font-semibold text-slate-600 hover:text-indigo-600">← Back to Templates</a><p class="mt-2 text-sm text-slate-500">Demo rendering · Version {{ $template->version }} · {{ Str::headline($template->status) }} · {{ strtoupper($template->source_type === 'latex' ? 'TEX' : $template->source_type) }}</p></div>
            <div class="flex gap-2"><button type="button" onclick="document.getElementById('admin-template-preview').contentWindow.print()" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">Print test</button><a href="{{ route('admin.templates.edit',$template) }}" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">Edit</a><form method="POST" action="{{ route('admin.templates.duplicate',$template) }}">@csrf<button class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Duplicate</button></form></div>
        </div>
        <section class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]">
            <div class="rounded-xl border border-slate-200 bg-slate-100 p-4 shadow-sm"><div class="mx-auto aspect-[210/297] w-full max-w-[794px] overflow-hidden bg-white shadow-xl"><iframe id="admin-template-preview" title="{{ $template->name }} preview" srcdoc="{{ e($renderedHtml) }}" class="h-full w-full border-0"></iframe></div></div>
            <aside class="h-fit rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
                <h2 class="font-semibold text-slate-900">Processing details</h2>
                <dl class="mt-4 divide-y divide-slate-100 text-sm"><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Source</dt><dd class="text-right font-semibold">{{ data_get($template->config,'source_original_name','Built-in HTML') }}</dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Type</dt><dd class="font-semibold uppercase">{{ $template->source_type === 'latex' ? 'TEX → HTML' : $template->source_type }}</dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Mapping</dt><dd class="font-semibold {{ data_get($template->config,'requires_mapping') ? 'text-amber-600' : 'text-emerald-600' }}">{{ data_get($template->config,'requires_mapping') ? count(data_get($template->config,'mapping_candidates',[])).' unresolved' : 'Complete' }}</dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Size</dt><dd class="font-semibold">{{ number_format((int)data_get($template->config,'source_size_bytes',0)/1024,1) }} KB</dd></div><div class="flex justify-between gap-3 py-3"><dt class="text-slate-500">Processed</dt><dd class="text-right font-semibold">{{ data_get($template->config,'processed_at') ? \Carbon\Carbon::parse(data_get($template->config,'processed_at'))->diffForHumans() : 'Legacy template' }}</dd></div></dl>
                @if(data_get($template->config,'requires_mapping'))<a href="{{ route('admin.templates.edit',$template) }}" class="mt-4 block rounded-lg bg-amber-500 px-3 py-2 text-center text-sm font-semibold text-white">Complete field mapping</a>@endif
                <p class="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">Detected placeholders</p><div class="mt-2 flex flex-wrap gap-1">@forelse(data_get($template->config,'detected_placeholders',[]) as $placeholder)<code class="rounded bg-indigo-50 px-1.5 py-1 text-[10px] text-indigo-700">@{{ {{ $placeholder }} }}</code>@empty<span class="text-xs text-slate-400">Legacy metadata</span>@endforelse</div>
            </aside>
        </section>
    </div>
</x-admin-layout>
