@php($editing = (bool) $managedUser)
<x-admin-layout :title="$editing ? 'Edit User' : 'Create User'">
    @include('admin.access._tabs')
    <div class="mx-auto max-w-4xl">
        <a href="{{ route('admin.users') }}" class="mb-5 inline-flex text-sm font-semibold text-slate-600 hover:text-indigo-600">← Back to Users</a>
        <form method="POST" enctype="multipart/form-data" action="{{ $editing ? route('admin.users.update', $managedUser) : route('admin.users.store') }}" class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm" x-data="{ saving: false, preview: null }" @submit="saving = true">
            @csrf @if($editing) @method('PATCH') @endif
            <div class="border-b border-slate-200 px-6 py-5"><h2 class="font-display text-lg font-semibold">{{ $editing ? 'Edit user account' : 'Create user account' }}</h2><p class="mt-1 text-sm text-slate-500">Account details, profile image, status, and role access.</p></div>
            <div class="grid gap-6 p-6 md:grid-cols-[180px_1fr]">
                <div><p class="mb-2 text-sm font-semibold text-slate-700">Profile Image</p><div class="relative h-32 w-32"><x-ui.avatar :user="$managedUser ?? auth()->user()" size="h-32 w-32" text-size="text-3xl" class="ring-4 ring-slate-100" /><template x-if="preview"><img :src="preview" class="absolute inset-0 h-32 w-32 rounded-full object-cover ring-4 ring-indigo-100" alt="Selected profile image"></template></div><label class="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold hover:bg-slate-50"><x-ui.icon name="photo" class="h-4 w-4" /> Choose image<input type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="if ($event.target.files[0]) preview = URL.createObjectURL($event.target.files[0])"></label><p class="mt-2 text-xs text-slate-500">JPG, PNG or WEBP. Maximum 2MB.</p>@error('profile_photo')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
                <div class="grid gap-5 sm:grid-cols-2">
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Full Name *</span><input name="name" value="{{ old('name', $managedUser?->name) }}" required class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">@error('name')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Email *</span><input name="email" type="email" value="{{ old('email', $managedUser?->email) }}" required class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">@error('email')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Phone</span><input name="phone" value="{{ old('phone', $managedUser?->phone) }}" class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">@error('phone')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Status *</span><select name="status" required class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200"><option value="active" @selected(old('status', $managedUser?->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $managedUser?->status) === 'inactive')>Inactive</option></select></label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Timezone *</span><input name="timezone" value="{{ old('timezone', $managedUser?->timezone ?? 'UTC') }}" required class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">@error('timezone')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Language *</span><select name="locale" required class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">@foreach(['en' => 'English','en-GB' => 'English (UK)','ur' => 'Urdu'] as $value => $label)<option value="{{ $value }}" @selected(old('locale', $managedUser?->locale ?? 'en') === $value)>{{ $label }}</option>@endforeach</select>@error('locale')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Password {{ $editing ? '' : '*' }}</span><input name="password" type="password" @required(!$editing) autocomplete="new-password" class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200">@if($editing)<span class="mt-1 block text-xs text-slate-500">Leave blank to keep the current password.</span>@endif @error('password')<span class="text-xs text-rose-600">{{ $message }}</span>@enderror</label>
                    <label class="block"><span class="mb-1.5 block text-sm font-semibold">Confirm Password {{ $editing ? '' : '*' }}</span><input name="password_confirmation" type="password" @required(!$editing) autocomplete="new-password" class="w-full rounded-lg border-slate-200 text-sm focus:border-indigo-500 focus:ring-indigo-200"></label>
                </div>
            </div>
            <div class="border-t border-slate-200 px-6 py-5"><h3 class="font-display font-semibold">Assign Roles</h3><p class="mt-1 text-sm text-slate-500">Roles determine the user’s administrative capabilities.</p><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($roles as $role)<label class="flex cursor-pointer gap-3 rounded-lg border border-slate-200 p-3 hover:border-indigo-300"><input type="checkbox" name="role_ids[]" value="{{ $role->id }}" @checked(in_array($role->id, old('role_ids', $managedUser?->roles?->pluck('id')->all() ?? []))) class="mt-0.5 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"><span><span class="block text-sm font-semibold">{{ Str::headline($role->name) }}</span><span class="text-xs text-slate-500">{{ $role->permissions_count }} permissions</span></span></label>@endforeach</div>@error('role_ids.*')<p class="mt-2 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
            <div class="flex justify-end gap-3 border-t border-slate-200 bg-slate-50 px-6 py-4"><a href="{{ route('admin.users') }}" class="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold">Cancel</a><button :disabled="saving" class="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-semibold text-white disabled:opacity-60" x-text="saving ? 'Saving...' : '{{ $editing ? 'Update User' : 'Create User' }}'">Save</button></div>
        </form>
    </div>
</x-admin-layout>
